# Generated by Django 5.0.6 on 2024-07-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('categoryId', models.IntegerField(default='1')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, max_length=12)),
            ],
        ),
    ]
